project:
  type: website
    
website:
  site-url: https://archaeothommy.github.io/hms-rip-meeting/
  repo-url: https://github.com/archaeothommy/hms-rip-meeting/
  favicon: favicon.png
  title: "![Logo HMS](https://historicalmetallurgy.org/wp-content/uploads/2020/02/Logo120.png){height=60px}"
  navbar:
    left:
      - href: index.qmd
        text: "Research in Progress Meeting 2024 | tba  | online"
#      - href: https://forms.gle/4WL3oqG4vHh1F7ti7
#        text: "Submit Abstract"
#      - href: https://forms.gle/dzQemocN3TtX6LhF7
#        text: "Register"
    right: 
      - href: archive.qmd
        text: "Archive"
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    backgroundcolor: white
    linkcolor: "#db2929"
    toc: true
    toc-location: left
    link-external-newwindow: true

execute:
  freeze: auto
  