project:
  type: website

website:
  title: "![Logo HMS](https://historicalmetallurgy.org/wp-content/uploads/2020/02/Logo120.png){height=60px}"
  navbar:
    left:
      - href: index.qmd
        text: "Research in Progress Meeting 2023 | 22^nd^ April, 2023 | online (Zoom)"
#      - href: 
#        text: "Submit Abstract"
#      - href: 
#        text: "Registration"
    right: 
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    backgroundcolor: white
    linkcolor: "#db2929"
    toc: true

execute:
  freeze: auto
  