project:
  type: website
  output-dir: docs

website:
  title: "hms-rip23"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    backgroundcolor: white
    linkcolor: "#db2929"
    toc: true

execute:
  freeze: auto
  