---
title: "Meeting Archive"
---


## Meeting 2024

Date: 22 November 2024  
Participants: ca. 40 participants constantly in Zoom meeting  
Student award winner: Léa Chanal

### Presentations
* Rithik Pramod: [Beyond the miniature: An exploration of the artistic and religious dimensions of Tamil Nadu's bronze scupltures](abstracts/2024-1.qmd)
* Sabikun Naher, Md. Ashraful Alam: [Surface enrichment and deterioration patterns of two silver punch-marked coins from Tekttha, Naogaon, Bangladesh: An X-ray diffraction analysis](abstracts/2024-2.qmd)
* Meghan Parker, Ineke Joosten, Rosalijn van IJken: [Degradation of tin foils on historic Leyden jars](abstracts/2024-3.qmd)
* Katherine Rothwell, Andrew R. C. Grigg, Nicola Grahamslaw, James M. Byrne: [Characterising the corrosion of the SS Great Britain using handheld XRF](abstracts/2024-4.qmd)
* Julia Montes-Landa, Mark Box, Caroline Archer-Parré, Ann-Marie Carey, Maciej Pawlikowski, Marcos Martinón-Torres: [Reconstructing letterpress technology through the Baskerville punches: new scientific data to reverse-engineer a practically lost craft](abstracts/2024-5.qmd)
* Anaïs Walsdorf: [Race and civilisation in John Percy’s Metallurgy (1864)](abstracts/2024-6.qmd)
* Donald B. Wagner: [The archaeometallurgy of iron: An introduction for students of archaeology](abstracts/2024-8.qmd)
* Kutsi Akcicek, Sinan Acikgoz, Heather Viles: [Comparative optical, chemical, and mechanical characterisation of 18th century and modern re-rolled wrought irons](abstracts/2024-9.qmd)
* Tobias Heal, Alexandre Disser, Thomas Fischbach: [Acies Ferri: Construction and provenance of Merovingian seaxes from 5th-8th century Alsace](abstracts/2024-10.qmd)
* Léa Chanal, Guillaume Sarah, Florian Téreygeol: [Improving our knowledge of the circulation of copper and its alloys: the case of the French Pyrenees at the end of the Middle Ages](abstracts/2024-11.qmd)
* Alexandre Disser: [Recent and ongoing developments of a database related to iron metallurgy](abstracts/2024-12.qmd)
* Lilo Nilima: [Marginalization and perception: The role of disabled in archaeometallurgical societies of Southern highlands, Tanzania.](abstracts/2024-13.qmd)
* Peter Northover, Vanessa Cheel: [Historical Metallurgy Society Projects: Glossary of Terms and Atlas of Microstructures](abstracts/2024-15.qmd)
* Frank Hulek, Yannis Bassiakos, Eleni Filippaki: [Studying the different mineralizations of Laurion through a combined geological and archaeological approach](abstracts/2024-16.qmd)
* Ivan Stepanov, Khaled Al-Bashaireh, Michael Brauns: [The first insight into the origins of Ammonite iron through Os isotope analyses of iron arrowheads from the Late Iron Age cemetery of Tell El Mazar, Jordan](abstracts/2024-17.qmd)
* Paul Rondelez, Rowan Taylor: [New insights in early bloom processing](abstracts/2024-18.qmd)
* Joshua Koss, Patrick Thaden: [An experimental Investigation of Medieval Helmet Forging Techniques](abstracts/2024-19.qmd)|
* Richard Williams: [Characteristics of malleable irons by the fining techniques used in their manufacture](abstracts/2024-20.qmd)

Download abstracts as [PDF](assets/HMS-RiP2024_Abstracts.pdf). 

## Meeting 2023-2

Date: 24 November 2023  
Participants: ca. 60 participants constantly in Zoom meeting  
Student award winner: Evgeny Shnyr

### Presentations
* Diya Mukherjee: *Learning, experience and experiment of ancient copper smelting technology with the reference to Harappan culture*
* Farhanath K: *Iron technology and its role in shaping socio-cultural dynamics in ancient India during the 1^st^ milllenium BC: A multifaceted perspective*
* Ivan Stepanov, Michael Brauns, Hannes Knapp, Anna Langgartner & Michael Geschwinde: *Provenance and manufacturing technology of iron catapult bolts as a reflection of the Roman iron supply chains at the Germanic limes*
* Fabio Spagiari: *On the tracks of the blacksmiths: Metallurgy tools of the Roman age from northern Italy*
* Sulaiman Ahmed Abiodun: *Iron metallurgy in Medieval and Post-Medieval Ile Ife, Nigeria: Recent excavation at Iyekere *
* Simon Aumônier & Vanessa Cheel: *Mounted archaeometallurgical samples: Resin ageing effects and remounting for durability*
* Linn Nordvall: *Plano-convex copper ingots in Scandinavia: A methodological approach*
* David A. Scott: *Technical examination of a Lydian kline (bed): A unique example of Lydian sophisticated metallurgy*
* Sabine Plummer & Victoria Sainsbury: *Material analysis of metal inlays in ball-headed clubs from the Ashmolean Tradescant Collection*
* Evgeny Shnyr: *Data science in the service of archaeology: Pinpointing the geographical source of ancient lead-containing metals using machine learning*
* Thomas Rose, Sabine Klein, Katrin J. Westner & Yiu-Kang Hsu: *News from the GlobaLID engine room*
* Peter Bray & Philippa Walton: *A new copper alloy chemical analysis project for the UK 1^st^ Millennium AD, employing Microwave Plasma-Atomic Emission Spectrometry (MP-AES): REMADE, University of Reading*
* Malou Blank & Serena Sabatini: *Copper in the Early Neolithic, a TRB flat axe from inland Western Sweden*
* Mathias Mehofer & Mario Gavranovic: *Archaeometallurgical studies on the Bronze Age metal procurement on the western and central Balkan*
* Stephanie Aulsebrook: *The complex lives of ‘meaningless scraps’: Reuse and upcycling at Late Bronze Age Mycenae*

Download programme as [PDF](assets/2023-2_Programme.pdf).

## Meeting 2023-1

Date: 22 April 2023  
Participants: ca. 35 participants constantly in Zoom meeting  
Student award winner: Raluca Lazarescu

### Presentations

* N. Kucukarslan, T. Ota, C. Potiszil, K. Kobayashi, E. Nakamura, S. Omura: *Searching for clues about the early iron history in Central Anatolia*
* M. Charlton, X. (Janice) Li, A. Bevan: *Emperor Qin Shi Huang’s iron*
* X. Michel-Tanaka: *The evolution of furnace wall making in japanese traditional iron smelting*
* E. Vodyasov, O. Zaitceva, M. Vavulin: *Nomadic iron production in the Altai Mountains in the 1^st^ millennium AD: Advanced technology of box-shape furnaces*
* M. Charlton: *New approaches to old methods: archaeometallurgical analysis at the UCL Institute of Archaeology*
* B. Cornelis, A. Wittke, D. Berger: *Disentangling the Sögel-Wohlde blade tradition of the Nordic Bronze Age through a multi-proxy approach*
* M. Odler: *News on the research of early ancient Egyptian and Nubian copper metallurgy*
* I. Calgaro, M. Radivojevic, M. Altaweel, A. S. Yermolayeva: *Metal production at 2nd millennium BC Taldysai (Central Kazakhstan): An update of research*
* A. Rodzinka: *Complex metallurgy of the Bronze Age-Iron Age transition in Iran: Archaeomaterials and forensic investigations*
* I. Stepanov, M. Brauns, U. Avner, N. Lockhoff, A. Eliyahu-Behar: *Investigation of provenance of Nabataean iron tools from the Southern Levant via a combined approach of osmium isotopy and trace element analyses*
* R. Lazarescu, C. Fenwick, Y. Bokbot, M. Charlton, D. Mattingly, M. Sterry: *Copper production in the medieval Moroccan Sahara*
* J. English, J. Prus: *What were they thinking of? Metalworkers’ thought before modern chemistry*
* A. B. Daoust: *An introduction to the Roman blacksmith Project: Identity, labour division, and status in funerary imagery*
* R. J. H. Wanhill, O. Oudbashi: *Fractography and metallography of some heritage metals*
* O. Oudbashi, F. Carò: *Chemical-microstructural characterization of metalworking technology during the Early Islamic Period of Iran (7^th^ to 14^th^ centuries CE)*
* S. Greiff: *The 19^th^ c. blast furnace of the Gräfenbach iron works in Germany*
